services:
  mysql:
    image: mysql:8.3  # Обновленная версия MySQL
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: airline_db
    ports:
      - "3306:3306"
    networks:
      - airline-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s

  airline:
    image: olenamyroshnykova/airline:latest
    container_name: airline
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/airline_db?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: your_password
    ports:
      - "8080:8080"
    networks:
      - airline-network

networks:
  airline-network:
    driver: bridge

